version: '3'
services:
  mail-demo-database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Demo@123A
    ports:
      - 1433:1433
    volumes:
      - data:/var/opt/mssql

volumes:
  data:

